(define (average a b) (/ (+ a b) 2))
(define make-point cons)
(define get-x car)
(define get-y cdr)
(define (print-point p)
  (display "(")
  (display (get-x p))
  (display ", ")
  (display (get-y p))
  (display ")")
  (newline))
(define (make-segment sp ep)
  (cons sp ep))
(define (start-segment s)
  (car s))
(define (end-segment s)
  (cdr s))
(define (mid-point s)
  (make-point (average (get-x (start-segment s)) 
		       (get-x (end-segment s)))
	      (average (get-y (start-segment s))
		       (get-y (end-segment s)))))
(define (make-rect lhp w h)
  ;lhp - left highest point, w - width, h - height.
  (cons lhp
	(make-point (- w (get-x lhp))
		    (- h (get-y lhp)))))
(define (get-w r) 
  (+ (get-x (car r))
     (get-x (cdr r))))
(define (get-h r)
  (+ (get-y (car r))
     (get-y (cdr r))))
(define (get-area r)
  (* (get-w r)
     (get-h r)))
(define (get-perimeter r)
  (+ (get-w r)
     (get-h r)))
