(define (factor val a)
  (define (iter res count)
    (if (= (remainder res a) 0)
      (iter (/ res a) (+ count 1))
      count))
  (iter val 0))
(define (n-cons a b)
  (* (expt 2 a)
     (expt 3 b)))
(define (n-car x)
  (factor x 2))
(define (n-cdr x)
  (factor x 3))

