(define (same-parity fv . l)
  (define (same? val)
    (even? (+ fv val)))
  (define (same l)
    (cond ((null? l) '())
	  ((same? (car l)) (cons (car l) 
				 (same (cdr l))))
	  (else (same (cdr l)))))
  (cons fv (same l)))
